# Generated by Django 6.0.6 on 2026-07-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
