# Generated by Django 6.0.6 on 2026-08-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_patientprofile_phone_alter_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True),
        ),
    ]
