# Generated by Django 6.0.6 on 2026-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_remove_patientprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='referral_type',
            field=models.CharField(choices=[('self', 'Self'), ('doctor', 'Doctor')], default='self', max_length=10),
        ),
    ]
