"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file located at the project root
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the old insecure dev key ONLY if nothing is set in .env,
# so local setups that haven't updated their .env yet don't break.
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-m#_qjko(x5vov($6dawx(rg0jrbir-0vf@2li5$hm1v89gk$x_',
)

# SECURITY WARNING: don't run with DEBUG turned on in production!
# Reads "True"/"False" (case-insensitive) from .env; defaults to True so
# local development keeps working with no .env changes required.
DEBUG = os.getenv('DJANGO_DEBUG', 'True').strip().lower() == 'true'

# Comma-separated list in .env, e.g. ALLOWED_HOSTS=example.com,www.example.com
# Defaults to localhost/127.0.0.1 for local development.
_allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom Apps
    'accounts.apps.AccountsConfig',
    'laboratory',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# =========================================================================
# DATABASE ENGINE CONFIGURATION (single, unified database)
# =========================================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]

AUTH_USER_MODEL = 'accounts.User'


# =========================================================================
# APPLICATION DOMAIN CONFIGURATION
# =========================================================================
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')


# =========================================================================
# EMAIL CONFIGURATION (Loaded from .env)
# =========================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f"LabPortal Medical Diagnostics <{EMAIL_HOST_USER}>"


# =========================================================================
# PAYMENT GATEWAY CONFIGURATION (Loaded from .env)
# =========================================================================
# All values below default to the OFFICIAL public sandbox/UAT credentials
# published by each provider's developer docs, so the booking -> payment
# flow works out of the box in DEBUG mode without any setup. Override every
# one of these in your .env file with your real merchant credentials before
# going live -- the sandbox values will never move real money, but they
# will also never work in production.

# --- eSewa (ePay v2) --------------------------------------------------
# Official eSewa UAT/sandbox values (developer.esewa.com.np/pages/Test-credentials)
ESEWA_PRODUCT_CODE = os.getenv('ESEWA_PRODUCT_CODE', 'EPAYTEST')
ESEWA_SECRET_KEY = os.getenv('ESEWA_SECRET_KEY', '8gBm/:&EnhH.1/q')
ESEWA_PAYMENT_URL = os.getenv('ESEWA_PAYMENT_URL', 'https://rc-epay.esewa.com.np/api/epay/main/v2/form')
ESEWA_STATUS_CHECK_URL = os.getenv('ESEWA_STATUS_CHECK_URL', 'https://rc.esewa.com.np/api/epay/transaction/status/')
# Switch to the two lines below (and your real product code/secret) for production:
#   ESEWA_PAYMENT_URL=https://epay.esewa.com.np/api/epay/main/v2/form
#   ESEWA_STATUS_CHECK_URL=https://esewa.com.np/api/epay/transaction/status/

# --- Khalti (ePayment / KPG v2) ---------------------------------------
# Sign up as a test merchant at https://test-admin.khalti.com to get a
# real test secret key -- there is no shared public one like eSewa's.
KHALTI_SECRET_KEY = os.getenv('KHALTI_SECRET_KEY', '')
KHALTI_INITIATE_URL = os.getenv('KHALTI_INITIATE_URL', 'https://dev.khalti.com/api/v2/epayment/initiate/')
KHALTI_LOOKUP_URL = os.getenv('KHALTI_LOOKUP_URL', 'https://dev.khalti.com/api/v2/epayment/lookup/')
# Switch to https://khalti.com/api/v2/epayment/{initiate,lookup}/ for production.

# --- Fonepay ------------------------------------------------------------
# Requires a merchant code + shared secret issued by Fonepay after
# merchant onboarding. Leave blank to keep the Fonepay option hidden.
FONEPAY_MERCHANT_CODE = os.getenv('FONEPAY_MERCHANT_CODE', '')
FONEPAY_SECRET_KEY = os.getenv('FONEPAY_SECRET_KEY', '')
FONEPAY_PAYMENT_URL = os.getenv('FONEPAY_PAYMENT_URL', 'https://dev-clientapi.fonepay.com/api/merchantRequest')
# Switch to https://clientapi.fonepay.com/api/merchantRequest for production.

# --- NIC Asia Bank (manual direct deposit / bank transfer) -------------
# NIC Asia doesn't expose a self-service merchant API for small
# businesses, so this option is a "pay by bank transfer, then tell us
# the reference number" flow that staff verify from the Admin Dashboard.
NIC_ASIA_ACCOUNT_NAME = os.getenv('NIC_ASIA_ACCOUNT_NAME', 'LabPortal Medical Diagnostics Pvt. Ltd.')
NIC_ASIA_ACCOUNT_NUMBER = os.getenv('NIC_ASIA_ACCOUNT_NUMBER', '0010123456789012')
NIC_ASIA_BRANCH = os.getenv('NIC_ASIA_BRANCH', 'New Road Branch, Kathmandu')

# =========================================================================
# AI REPORT CHAT ASSISTANT (Anthropic API)
# =========================================================================
# Lets a patient ask plain-language questions about their own completed
# report. Get a key from https://console.anthropic.com -- leave blank to
# keep the "Ask AI" button disabled/hidden.
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
ANTHROPIC_MODEL = os.getenv('ANTHROPIC_MODEL', 'claude-sonnet-5')


from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

LOGOUT_REDIRECT_URL = 'home'